mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

external-controller: 127.0.0.1:9090
ipv6: false

dns:
  enable: true
  listen: 0.0.0.0:1055
  ipv6: false
  enhanced-mode: fake-ip

  nameserver:
    - 1.1.1.1
    - 8.8.8.8


proxies:
  - name: NY-VPS
    type: vless
    server: YOUR_NY_IP
    port: 443
    uuid: YOUR_UUID
    network: tcp
    tls: true
    servername: www.cloudflare.com
    skip-cert-verify: true

    reality-opts:
      public-key: YOUR_PUBLIC_KEY
      short-id: a1b2c3d4

    client-fingerprint: chrome


proxy-groups:

  - name: PROXY
    type: select
    proxies:
      - NY-VPS
      - DIRECT

  - name: UPLOAD
    type: select
    proxies:
      - NY-VPS


rules:

  # 本地
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT

  # 中国直连
  - GEOIP,CN,DIRECT

  # 🎬 YouTube上传
  - DOMAIN-SUFFIX,googlevideo.com,UPLOAD
  - DOMAIN-SUFFIX,youtube.com,UPLOAD
  - DOMAIN-SUFFIX,ytimg.com,UPLOAD

  # Google服务
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-SUFFIX,googleapis.com,PROXY

  # 默认
  - MATCH,PROXY
